//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CER.Json {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CER.Json.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control character in string..
        /// </summary>
        internal static string ControlCharacterInString {
            get {
                return ResourceManager.GetString("ControlCharacterInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character {0} in constant {1}: expected {2}..
        /// </summary>
        internal static string InvalidCharacterInConstant {
            get {
                return ResourceManager.GetString("InvalidCharacterInConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence {0}..
        /// </summary>
        internal static string InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("InvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unicode hexadecimal {0}..
        /// </summary>
        internal static string InvalidUnicodeHexadecimal {
            get {
                return ResourceManager.GetString("InvalidUnicodeHexadecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; has more than one entry in the object..
        /// </summary>
        internal static string KeyNotUnique {
            get {
                return ResourceManager.GetString("KeyNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No array to end..
        /// </summary>
        internal static string NoArrayToEnd {
            get {
                return ResourceManager.GetString("NoArrayToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No object to end..
        /// </summary>
        internal static string NoObjectToEnd {
            get {
                return ResourceManager.GetString("NoObjectToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers must have at least one digit after the decimal point..
        /// </summary>
        internal static string NumbersMustHaveAtLeastOneDigitAfterDecimalPoint {
            get {
                return ResourceManager.GetString("NumbersMustHaveAtLeastOneDigitAfterDecimalPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers must have at least one digit in an exponent..
        /// </summary>
        internal static string NumbersMustHaveAtLeastOneDigitInExponent {
            get {
                return ResourceManager.GetString("NumbersMustHaveAtLeastOneDigitInExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} character {1}: {2}.
        /// </summary>
        internal static string TextLocationMessage {
            get {
                return ResourceManager.GetString("TextLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected array end..
        /// </summary>
        internal static string UnexpectedArrayEnd {
            get {
                return ResourceManager.GetString("UnexpectedArrayEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected array start..
        /// </summary>
        internal static string UnexpectedArrayStart {
            get {
                return ResourceManager.GetString("UnexpectedArrayStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character {0}..
        /// </summary>
        internal static string UnexpectedCharacter {
            get {
                return ResourceManager.GetString("UnexpectedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected colon..
        /// </summary>
        internal static string UnexpectedColon {
            get {
                return ResourceManager.GetString("UnexpectedColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected comma..
        /// </summary>
        internal static string UnexpectedComma {
            get {
                return ResourceManager.GetString("UnexpectedComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file..
        /// </summary>
        internal static string UnexpectedEndOfFile {
            get {
                return ResourceManager.GetString("UnexpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file in constant..
        /// </summary>
        internal static string UnexpectedEndOfFileInConstant {
            get {
                return ResourceManager.GetString("UnexpectedEndOfFileInConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file in string..
        /// </summary>
        internal static string UnexpectedEndOfFileInString {
            get {
                return ResourceManager.GetString("UnexpectedEndOfFileInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character {0} in number..
        /// </summary>
        internal static string UnexpectedNumberCharacter {
            get {
                return ResourceManager.GetString("UnexpectedNumberCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected object end..
        /// </summary>
        internal static string UnexpectedObjectEnd {
            get {
                return ResourceManager.GetString("UnexpectedObjectEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected object start..
        /// </summary>
        internal static string UnexpectedObjectStart {
            get {
                return ResourceManager.GetString("UnexpectedObjectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot have leading positive sign..
        /// </summary>
        internal static string ValueCannotHaveLeadingPositiveSign {
            get {
                return ResourceManager.GetString("ValueCannotHaveLeadingPositiveSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value contains an unpaired surrogate..
        /// </summary>
        internal static string ValueContainsAnUnpairedSurrogate {
            get {
                return ResourceManager.GetString("ValueContainsAnUnpairedSurrogate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value contains a control character..
        /// </summary>
        internal static string ValueContainsControlCharacter {
            get {
                return ResourceManager.GetString("ValueContainsControlCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value contains invalid escape sequence {0}..
        /// </summary>
        internal static string ValueContainsInvalidEscape {
            get {
                return ResourceManager.GetString("ValueContainsInvalidEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value contains invalid hexadecimal number {0}..
        /// </summary>
        internal static string ValueContainsInvalidHex {
            get {
                return ResourceManager.GetString("ValueContainsInvalidHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value contains an unescaped double quote..
        /// </summary>
        internal static string ValueContainsUnescapedDoubleQuote {
            get {
                return ResourceManager.GetString("ValueContainsUnescapedDoubleQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value ends with incomplete escape sequence..
        /// </summary>
        internal static string ValueEndsWithIncompleteEscapeSequence {
            get {
                return ResourceManager.GetString("ValueEndsWithIncompleteEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value ends with incomplete unicode sequence..
        /// </summary>
        internal static string ValueEndsWithIncompleteUnicode {
            get {
                return ResourceManager.GetString("ValueEndsWithIncompleteUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null..
        /// </summary>
        internal static string ValueIsNull {
            get {
                return ResourceManager.GetString("ValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not whitespace. It can only contain spaces, linefeeds, carriage returns, and/or horizontal tabs..
        /// </summary>
        internal static string ValueNotWhitespace {
            get {
                return ResourceManager.GetString("ValueNotWhitespace", resourceCulture);
            }
        }
    }
}
