//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array.
        /// </summary>
        internal static string Array {
            get {
                return ResourceManager.GetString("Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (ASCII).
        /// </summary>
        internal static string AutoAscii {
            get {
                return ResourceManager.GetString("AutoAscii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (CP-1252).
        /// </summary>
        internal static string AutoCP1252 {
            get {
                return ResourceManager.GetString("AutoCP1252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (UTF-16 BE BOM).
        /// </summary>
        internal static string AutoUtf16BEBom {
            get {
                return ResourceManager.GetString("AutoUtf16BEBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (UTF-16 LE BOM).
        /// </summary>
        internal static string AutoUtf16LEBom {
            get {
                return ResourceManager.GetString("AutoUtf16LEBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (UTF-32 BE BOM).
        /// </summary>
        internal static string AutoUtf32BEBom {
            get {
                return ResourceManager.GetString("AutoUtf32BEBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (UTF-32 LE BOM).
        /// </summary>
        internal static string AutoUtf32LEBom {
            get {
                return ResourceManager.GetString("AutoUtf32LEBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (UTF-8).
        /// </summary>
        internal static string AutoUtf8 {
            get {
                return ResourceManager.GetString("AutoUtf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (UTF-8-BOM).
        /// </summary>
        internal static string AutoUtf8Bom {
            get {
                return ResourceManager.GetString("AutoUtf8Bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string Boolean {
            get {
                return ResourceManager.GetString("Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        internal static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{0}Check the file name and try again..
        /// </summary>
        internal static string OpenFailed {
            get {
                return ResourceManager.GetString("OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{0}Check the file name and try again..
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{0}Writing failed..
        /// </summary>
        internal static string WritingFailed {
            get {
                return ResourceManager.GetString("WritingFailed", resourceCulture);
            }
        }
    }
}
